string = "GCTACGAGAACTCTCCCTGCTACTGGTCCACGGCAGGGCGAATAACCACTTACCAGCTACCGGTGCATGTCGCCGTAGAAAACGTTTAGCAGTGGGGCTTTGACTAACTTGACGCACAGATGGCATGCTGCCATCGGGCTATTATACTACTAAACCTGCATGTTGTATGGCTTCGGAGGGTTGAAGCACTTAACGGGAGGAGGCGATATGTCCACCCCATGTGACATAGGCCGCGATGTATAATACGCCATTTAAAAAAGCTCTGGCACGCAGTCGATCCTAGTGGCTATGCGGCCGGCTCTCGACTTCGTGAAAGGCTCTAGCGGGTGTACTGTTCCCCATGTATTGCGGCGGCATAGCTCGGCACGGCGCCGACCACACACACTGTTCGACCGTATTTTGGCACACTTCGAGTTAACCCAGACTGTCTGCCGCCCCATCTAGCTACCGTTGCTGTGATTTGGACACTCCCAGCGTACTAGTCACCACGTAACGAGGCAGGTCCGTGATAGCCCTAACTTATACACATACTTACTTGTGGGAAGCGGAAGGTGCGGGTTGGTCATGCCAAAGCCACATCGGCAAGAGTCTGTGGATTGCTCCTGCAGACTCCAGAAAGTGATCTGTTGGTAATTACCCTTTTTAATGCCTTCACAAGTCGCACATGAACCCCTCTAAGTAATCCCCTGAAGTTTAACTGGCTAGACTTTAGCGGCACATGGTGCTGATCTGGAGTGATCAGTCAAGTACCCCTCATATGTACGGGTTTTTAACCTCTCGTTAGCGCCGTCACTGGGGGGAGAACTTAGTAGATTAGTTAACCCCGACCCGGGGCCACCTCCACCCTCGGCCCGACGTTACTGGTTCAAAAGAGCTAATTTGGTTTCTTAGGAAGAAATCCCACCGTGCGTAATAAACTCGACCAAAACGTATTGTGGATGGCCAGGCTCATTATGAAAGTATGGTTGAAT"
from Bio.Seq import Seq
seq = Seq(string)
#print(str(seq.count("A"))+' '+str(seq.count("C"))+' '+str(seq.count("G"))+' '+str(seq.count("T")))



with open("rosalind_gbk.txt",'r') as file:
    search,start,end = file.read().split()

from Bio import Entrez
Entrez.email = "your_name@your_mail_server.com"
handle = Entrez.esearch(db="nucleotide", term=search+"[Organism]", datetype="PDAT",mindate=start, maxdate=end)
record = Entrez.read(handle)
print(record["Count"])
